[settings]
quiet = true
task_output = "interleave"
experimental = true
aqua.registries = ["https://github.com/KnickKnackLabs/bats-core"]

[plugins]
shiv = "https://github.com/KnickKnackLabs/vfox-shiv"

[tools]
"aqua:KnickKnackLabs/bats-core" = "1.14.0-kkl.3"
gum = "0.17.0"
jq = "1.8.1"
uv = "0.10.0"
"shiv:codebase" = "0.4"
"shiv:readme" = "0.3"

[_.codebase]
name = "whora"
lint = ["@all"]
